# golangci-lint configuration for newrelic-otel-shim

run:
  timeout: 5m
  tests: true

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - gofmt
    - goimports
    - gocritic
    - gosec
    - misspell
    - revive
    - unconvert

linters-settings:
  govet:
    check-shadowing: true
  revive:
    rules:
      - name: exported
        disabled: false
  gosec:
    excludes:
      - G402

issues:
  max-issues-per-linter: 0
  max-same-issues: 0