name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: ./v3/go.mod

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Download dependencies
        working-directory: ./v3
        run: go mod download

      - name: Verify dependencies
        working-directory: ./v3
        run: go mod verify

      - name: Run go vet
        working-directory: ./v3
        run: go vet ./...

      - name: Run staticcheck
        uses: dominikh/staticcheck-action@v1.4.0
        with:
          version: "latest"
          install-go: false

      - name: Run tests
        working-directory: ./v3
        run: |
          go test -v -race -coverprofile=coverage.out ./...

      - name: Generate coverage report
        working-directory: ./v3
        run: go tool cover -html=coverage.out -o coverage.html

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.out
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: false

  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: ./v3/go.mod

      - name: Build
        run: go build -v ./...

  compatibility:
    name: Go Version Compatibility
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ["1.23", "1.24", "1.25"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@v6
        with:
          go-version: ${{ matrix.go-version }}

      - name: Patch Go version
        working-directory: ./v3
        run: |
          go mod edit -go=${{ matrix.go-version }}
          go mod tidy -compat=${{ matrix.go-version }}

      - name: Download dependencies
        working-directory: ./v3
        run: go mod download

      - name: Build with Go ${{ matrix.go-version }}
        working-directory: ./v3
        run: go build -v ./...

      - name: Test with Go ${{ matrix.go-version }}
        working-directory: ./v3
        run: go test -v ./...

  integration:
    name: Drop-in Replacement Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: ./v3/go.mod

      - name: Run Drop-in Replacement Integration Test
        run: |
          cd integration-test
          chmod +x test-drop-in-replacement.sh
          ./test-drop-in-replacement.sh
